import '@core/commands/help'
import '@core/commands/start'
import '@core/commands/home'
import '@core/commands/miner'
import '@core/commands/go'
import '@core/commands/reset'
import '@core/commands/shop/categories'
import '@core/commands/shop/list'
